/* @macrome
 * @generatedby @bablr/macrome-generator-bablr
 * @generatedfrom ./productions.macro.js#5a914c908957f9e105a11d9b6dceffd70f2f22c4
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import { spam as m } from '@bablr/boot';
import { getCooked } from '@bablr/agast-helpers/tree';
import { eat, eatMatch } from './grammar.js';
import { EmbeddedMatcher } from './symbols.js';
import { getEmbeddedMatcher } from '@bablr/agast-vm-helpers/deembed';
import { buildPropertyMatcher } from './builders.js';
import { buildEmbeddedMatcher } from '@bablr/agast-vm-helpers/builders';
export function* List({
  props
}) {
  const {
    element,
    separator,
    allowHoles = false,
    allowTrailingSeparator = true
  } = props;
  if (getCooked(getEmbeddedMatcher(separator).properties.refMatcher?.node.properties.name?.node.properties.content.node)) {
    yield eat(buildEmbeddedMatcher(buildPropertyMatcher(getEmbeddedMatcher(separator).properties.refMatcher?.node, null, m.ArrayNodeMatcher`[]`)));
  }
  yield eat(buildEmbeddedMatcher(buildPropertyMatcher(getEmbeddedMatcher(Array.isArray(element) ? element[0] : element).properties.refMatcher?.node, null, m.ArrayNodeMatcher`[]`)));
  let sep,
    it,
    anySep = false;
  for (;;) {
    it = yield eatMatch(...(Array.isArray(element) ? element : [element]));
    if (it || allowTrailingSeparator) {
      sep = yield eatMatch(separator);
      anySep ||= sep;
    } else {
      sep = null;
    }
    if (!(sep || allowHoles)) break;
  }
}
export function* Any({
  props: {
    value: alternatives
  }
}) {
  for (const alternative of alternatives) {
    if (Array.isArray(alternative)) {
      if (yield eatMatch(...alternative)) break;
    } else if (alternative.type === EmbeddedMatcher) {
      if (yield eatMatch(alternative)) break;
    } else {
      throw new Error();
    }
  }
}
export function* All({
  props: {
    value: matchers
  }
}) {
  for (const matcher of matchers) {
    if (Array.isArray(matcher)) {
      yield eat(...matcher);
    } else {
      yield eat(matcher);
    }
  }
}
export function* Optional({
  props: {
    value: matcher
  }
}) {
  yield eatMatch(matcher);
}
export function* Literal({
  ctx,
  intrinsicValue
}) {
  if (!intrinsicValue) throw new Error('Intrinsic productions must have value');
  yield eat(ctx.sourceTextFor(intrinsicValue.value));
}
export const Keyword = Literal;
export const Punctuator = Literal;
export const Space = Literal;